name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-22.04
    name: FreeBSD ci
    steps:
    - uses: actions/checkout@v4
    - name: FreeBSD
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y curl

        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs > rustup.sh
          chmod +x ./rustup.sh
          ./rustup.sh -y -v --default-toolchain=nightly
          cargo build
