name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install cross-compiling deps
      run: |
        sudo apt-get -y update
        sudo apt-get install -y libssl-dev pkg-config
    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@master
      with:
          toolchain: nightly
          targets: x86_64-unknown-freebsd
          components: rust-src
    - name: Install cargo-zigbuild
      run: cargo install cargo-zigbuild
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo zigbuild --target x86_64-unknown-freebsd
    - name: Upload
      uses: actions/upload-artifact@v3.1.3
      with:
        name: dll_release
        path: /home/runner/work/mljboard/mljboard/target/x86_64-unknown-freebsd/release/mljboard
    - name: debug
      run:  ls -halt /home/runner/work/mljboard/mljboard/target/
